name: Build test

on:
  push: # run on every push
    paths-ignore: # do not run when only these files are modified
      - 'doc/**'
  pull_request:
    branches:
      - master
      - dev
    paths-ignore: # do not run when only these files are modified
      - 'doc/**'

jobs:
  build_ubuntu:
    name: Build job on Ubuntu

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        libprotobuf-dev libboost-program-options-dev protobuf-compiler
		sudo python3 -m pip install pytest meson
		wget https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-linux.zip
		unzip ninja-linux.zip
		chmod 755 ninja
		sudo chown root:root ninja
		sudo mv -fv ninja /usr/local/bin
		ninja --version
		meson --version
		wget https://github.com/libfuse/libfuse/releases/download/fuse-3.10.0/fuse-3.10.0.tar.gz
		tar xzf fuse-3.10.0.tar.gz
		cd fuse-3.10.0
		mkdir build
		cd build
		meson ..
		ninja
		sudo ninja install
    - name: Run CMake
      run: cmake -B build/
    - name: Build
      run: cd build/ && make
        
  build_osx:
    name: Build job on MacOS

    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install dependencies
      run: |
          brew install protobuf boost
          brew cask install osxfuse
    - name: Run CMake
      run: cmake -B build/
    - name: Build
      run: cd build/ && make
